# Generated by Django 4.2.7 on 2025-09-13 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbenchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_query_results_format', models.CharField(choices=[('table', 'Table'), ('csv', 'CSV'), ('json', 'JSON')], default='table', max_length=20)),
                ('query_timeout', models.IntegerField(default=120)),
                ('max_query_results', models.IntegerField(default=2000)),
                ('batch_size', models.IntegerField(default=200)),
                ('enable_rollback_on_error', models.BooleanField(default=True)),
                ('timezone_preference', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(default='HH:mm:ss', max_length=20)),
                ('api_timeout', models.IntegerField(default=60)),
                ('debug_mode', models.BooleanField(default=False)),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workbench_settings',
            },
        ),
        migrations.CreateModel(
            name='SalesforceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('server_url', models.URLField()),
                ('login_type', models.CharField(choices=[('oauth', 'OAuth'), ('standard', 'Username/Password'), ('advanced', 'Advanced')], default='oauth', max_length=20)),
                ('environment', models.CharField(choices=[('production', 'Production (login.salesforce.com)'), ('sandbox', 'Sandbox (test.salesforce.com)'), ('custom', 'Custom Domain')], default='production', max_length=20)),
                ('custom_domain', models.URLField(blank=True, null=True)),
                ('api_version', models.CharField(default='62.0', max_length=10)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('instance_url', models.URLField(blank=True, null=True)),
                ('salesforce_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('salesforce_username', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salesforce_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('bulk_query', 'Bulk Query'), ('bulk_insert', 'Bulk Insert'), ('bulk_update', 'Bulk Update'), ('bulk_upsert', 'Bulk Upsert'), ('bulk_delete', 'Bulk Delete'), ('metadata_deploy', 'Metadata Deploy'), ('metadata_retrieve', 'Metadata Retrieve')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='queued', max_length=20)),
                ('salesforce_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.salesforceconnection')),
            ],
            options={
                'db_table': 'async_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
